site_name: Citrix Provisioning Services 1903 PowerShell with Objects Programmerâ€™s Guide
site_description: Programmer's Guide for Citrix Provisioning Services 1903 with Objects
theme_dir: citrix-sdk
markdown_extensions:
  - admonition
  - codehilite
  - toc

pages:
- Index: index.md
